config/routes.rb
Rails.application.routes.draw do
  root 'game#settings'
  get 'start_game' => 'game#start_game'
  get 'board' => 'game#board'
  get 'move' => 'game#move'
  get 'game_over' => 'game#game_over'
  get 'game_history' => 'game#game_history'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale
   
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options={})
    { locale: I18n.locale  }
  end
end

app/controllers/game_controller.rb
require 'json'
require 'tic_tac_toes/core/presenter'
require 'tic_tac_toes/database/pg_wrapper'
require 'tic_tac_toes/ui/adapter'
require 'tic_tac_toes/ui/serializer'

class GameController < ApplicationController
  def start_game
    if params[:ai_type] && params[:order]
      game_state = TicTacToes::UI::Serializer.game_state(TicTacToes::UI::Serializer.new_board_structure,
                                                         params[:ai_type],
                                                         nil,
                                                         'unused_connection')
      TicTacToes::UI::Adapter.start_game(params[:order], game_state, self)
    else
      flash.now[:alert] = translate(:incomplete_form_alert)
      render :settings
    end
  end

  def move
    connection = PG.connect(dbname: ENV['TTT_DATABASE'],
                            host: ENV['TTT_HOST'],
                            port: ENV['TTT_PORT'],
                            user: ENV['TTT_USER'],
                            password: ENV['TTT_PASSWORD'])
    game_state = TicTacToes::UI::Serializer.game_state(params[:board],
                                                       params[:ai_type],
                                                       params[:move_history],
                                                       connection)
    TicTacToes::UI::Adapter.make_move(game_state, params[:move], self)
  end

  def game_history
    connection = PG.connect(dbname: ENV['TTT_DATABASE'],
                            host: ENV['TTT_HOST'],
                            port: ENV['TTT_PORT'],
                            user: ENV['TTT_USER'],
                            password: ENV['TTT_PASSWORD'])
    storage_wrapper = TicTacToes::Database::PGWrapper.new(connection)
    presenter = TicTacToes::Core::Presenter
    @game_history = presenter.game_history_strings(storage_wrapper)
  end

  def moves_were_made(game_state)
    @board = TicTacToes::UI::Serializer.board_structure(game_state)
    @ai_type = TicTacToes::UI::Serializer.ai_type(game_state)
    @move_history = TicTacToes::UI::Serializer.move_history(game_state)
    @predictions = JSON.generate({ spaces: TicTacToes::UI::Adapter.predictions(game_state) })
    render :board
  end

  def game_ended_in_draw(game_state)
    @board = TicTacToes::UI::Serializer.board_structure(game_state)
    @message = translate(:tie_game)
    render :game_is_over
  end

  def game_ended_in_winner(game_state, winning_token)
    @board = TicTacToes::UI::Serializer.board_structure(game_state)
    @message = translate(:winner, winning_token: winning_token == 'X' ? translate(:X) : translate(:O))
    render :game_is_over
  end
end

app/views/game/_board.html.erb
<table>
  <% [(0..2), (3..5), (6..8)].each do |row| %>
    <tr>
      <% row.each do |index| %>

        <td data-name="cell" data-id="<%= index %>">
          <% if board[index] %>
            <%= board[index] == 'X' ? translate(:X) : translate(:O) %>
          <% else %>
            <%= link_to "", move_path(board: board, ai_type: ai_type, move_history: move_history, move: index) %>
          <% end %> 
        </td>

      <% end %>
    </tr>
  <% end %>
</table>

app/views/game/board.html.erb
<script>
  $(function() {
    var predictions = JSON.parse('<%= raw @predictions %>')

    $('[data-name=cell]').hover(function(event) {
      var dataId = parseInt($(this).attr('data-id'))

      $('body').append('<div data-id="output"></div>')
        $('[data-id=output]').html(predictions.spaces[dataId])
      },
      function(event) {
        $('[data-id=output]').remove()
    })
  })
</script>

<%= render 'board', board: @board, ai_type: @ai_type, move_history: @move_history %>

app/views/game/choose_order.html.erb
<%= form_tag(start_game_path, method: "get") do %>

  <%= label_tag(:computer_type, translate(:select_difficulty)) %>
    <%= radio_button_tag(:computer_type, "EASY_AI") %>
    <%= label_tag(:computer_type_easy, translate(:easy)) %>
    <%= radio_button_tag(:computer_type, "MEDIUM_AI") %>
    <%= label_tag(:computer_type_medium, translate(:medium)) %>
    <%= radio_button_tag(:computer_type, "HARD_AI") %>
    <%= label_tag(:computer_type_hard, translate(:hard)) %>
    <br>

  <%= label_tag(:order, translate(:select_order)) %>
    <%= radio_button_tag(:order, "first") %>
    <%= label_tag(:order_first, translate(:first)) %>
    <%= radio_button_tag(:order, "second") %>
    <%= label_tag(:order_second, translate(:second)) %>
    <br>

  <%= hidden_field_tag(:locale, I18n.locale) %>

  <%= submit_tag(translate(:start_game)) %>

<% end %>

app/views/game/game_history.html.erb
<ul>
  <% @game_history.each do |history| %>
    <li><%= history %></li>
  <% end %>
</ul>

app/views/game/game_is_over.html.erb
<table>
  <% [(0..2), (3..5), (6..8)].each do |row| %>
    <tr>
      <% row.each do |index| %>

        <td>
          <%= @board[index] == 'X' ? translate(:X) : translate(:O) if @board[index] %>
        </td>

      <% end %>
    </tr>
  <% end %>
</table>

<%= @message %>

<button>
  <%= link_to translate(:play_again), root_path %>
</button>

app/views/game/settings.html.erb
<% if flash[:alert] %>
  <div><%= flash[:alert] %></div>
  <br>
<% end %>

<%= form_tag(start_game_path, method: "get") do %>

  <%= label_tag(:ai_type, translate(:select_difficulty)) %>
    <%= radio_button_tag(:ai_type, "EASY_AI") %>
    <%= label_tag(:ai_type_easy, translate(:easy)) %>
    <%= radio_button_tag(:ai_type, "MEDIUM_AI") %>
    <%= label_tag(:ai_type_medium, translate(:medium)) %>
    <%= radio_button_tag(:ai_type, "HARD_AI") %>
    <%= label_tag(:ai_type_hard, translate(:hard)) %>
    <br>

  <%= label_tag(:order, translate(:select_order)) %>
    <%= radio_button_tag(:order, "first") %>
    <%= label_tag(:order_first, translate(:first)) %>
    <%= radio_button_tag(:order, "second") %>
    <%= label_tag(:order_second, translate(:second)) %>
    <br>

  <%= hidden_field_tag(:locale, I18n.locale) %>

  <%= submit_tag(translate(:start_game)) %>

<% end %>

<%= link_to translate(:game_history), game_history_path %>

app/views/game/show.html.erb
<%= render 'board', board: @board %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= translate(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>